version: "3.8"
services:
  admin_web:
    build:
      context: ./admin_web
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    volumes:
      - ./admin_web:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - microservices_network
    restart: unless-stopped

  public_web:
    build:
      context: ./public_web
      dockerfile: Dockerfile.dev
    ports:
      - "3002:3000"
    volumes:
      - ./public_web:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - microservices_network
    restart: unless-stopped

  order:
    build:
      context: ./order
      dockerfile: Dockerfile.dev
    ports:
      - "3003:3000"
    volumes:
      - ./order:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - microservices_network
    restart: unless-stopped

  product:
    build:
      context: ./product
      dockerfile: Dockerfile.dev
    ports:
      - "3004:3000"
    volumes:
      - ./product:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - microservices_network
    restart: unless-stopped

  user-auth:
    build:
      context: ./user-auth
      dockerfile: Dockerfile.dev
    ports:
      - "3005:3000"
    volumes:
      - ./user-auth:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - microservices_network
    restart: unless-stopped

  # Kong API Gateway Services
  kong-gateway:
    image: kong/kong-gateway:3.4.1.0
    container_name: kong-gateway
    environment:
      KONG_DATABASE: off
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_URL: http://localhost:8002
      KONG_SSL: "on"
      KONG_SSL_CERT: /etc/kong/ssl/executehub.com.crt
      KONG_SSL_CERT_KEY: /etc/kong/ssl/executehub.com.key
      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl
    ports:
      - "80:8000" # HTTP
      - "443:8443" # HTTPS
      - "8001:8001" # Kong Admin API
      - "8002:8002" # Kong Admin GUI
      - "8444:8444" # Kong Admin API (HTTPS)
    volumes:
      - ./kong/kong.yml:/etc/kong/kong.yml
      - ./kong/ssl:/etc/kong/ssl
    networks:
      - microservices_network
    restart: unless-stopped

volumes:
  node_modules:

networks:
  microservices_network:
    driver: bridge
