_format_version: "2.1"
_transform: true

# Backend Services
services:
  - name: user-auth-service
    url: http://user-auth:3000
    routes:
      - name: user-auth-route
        paths:
          - /api/auth
        strip_path: true

  - name: product-service
    url: http://product:3000
    routes:
      - name: product-route
        paths:
          - /api/products
        strip_path: true

  - name: order-service
    url: http://order:3000
    routes:
      - name: order-route
        paths:
          - /api/orders
        strip_path: true

  # Web Applications
  - name: public-web
    url: http://public_web:3000
    routes:
      - name: public-web-route
        paths:
          - /
        hosts:
          - public.yourdomain.com
        methods:
          - GET

  - name: admin-web
    url: http://admin_web:3000
    routes:
      - name: admin-web-route
        paths:
          - /
        hosts:
          - admin.yourdomain.com
        methods:
          - GET
          - POST
          - PUT
          - DELETE

# Global Plugins
plugins:
  # Rate Limiting for Backend
  - name: rate-limiting
    config:
      policy: local
      second: 10
      minute: 600
      hour: 10000
      limit_by: ip
      
  # CORS Configuration
  - name: cors
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      headers:
        - Accept
        - Authorization
        - Content-Type
      exposed_headers:
        - X-Custom-Header
      max_age: 3600
      
  # JWT Authentication for Backend
  - name: jwt
    config:
      secret_is_base64: false
      claims_to_verify:
        - exp
      
  # Prometheus Metrics
  - name: prometheus
    config:
      metrics:
        - request_count
        - request_size
        - response_size
        - latency
        - status_code

  # Compression Plugin
  - name: response-transformer
    config:
      add:
        headers:
          - "Content-Encoding: gzip"
      
  # Request Size Limiting
  - name: request-size-limiting
    config:
      allowed_payload_size: 10 