name: Microservices CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - order
          - product
          - user-auth

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"
          cache-dependency-path: "${{ matrix.service }}/package-lock.json"

      - name: Install Dependencies
        working-directory: ${{ matrix.service }}
        run: npm ci

      - name: Lint
        working-directory: ${{ matrix.service }}
        run: npm run lint

      - name: Type Check
        working-directory: ${{ matrix.service }}
        run: npm run typecheck

      - name: Run Tests
        working-directory: ${{ matrix.service }}
        run: npm test

  build-web:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - admin_web
          - public_web

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"
          cache-dependency-path: "${{ matrix.service }}/package-lock.json"

      - name: Install Dependencies
        working-directory: ${{ matrix.service }}
        run: npm ci

      - name: Build
        working-directory: ${{ matrix.service }}
        run: npm run build

  build-docker:
    needs:
      - lint-and-test
      - build-web
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - order
          - product
          - user-auth

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile.dev
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:${{ github.sha }}
